Add and remove
romans-adi/To-Do-List pull request #2
Opened 2023-05-05 05:19 UTC by romans-adi

For this milestone:

- I used ES6 modules to restructure my project.
- All modules have descriptive names related to their functionality.
- To Do Model calls all functions as class methods. 
- All new tasks are not completed by default.
- Indexes updates on removing (map used).
- I used a textarea tag for description editing functionally. Since I prevent default behavior on the key 'Enter' press and save the changed value, there's no particular function for this created.

2023-05-05 06:02 UTC, OyePriscilla requested changes
Hi @romans-adi 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Removed all hardcoded items from the tasks array ✔️ 
Implement a function for adding, deleting and editing a new task ✔️ 
All changes to the To Do List saved in local storage ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 06:23 UTC, romans-adi commented on src/modules/remove.js
> +}
I agree that for better UI practice it is a good idea to add a remove button, but it was not a requirement.
Technically this logic was done with a clearButton and it was not forbidden.
Indexes still need to be fixed. Thank you!

2023-05-06 00:58 UTC, OyePriscilla requested changes
Hi @romans-adi 👏 👏 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Removed all hardcoded items from the tasks array ✔️
Implement a function for adding, deleting and editing a new task ✔️
All changes to the To Do List saved in local storage ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 00:58 UTC, OyePriscilla commented on src/modules/render.js
> +  // });
- [ ] Kindly remove this commented lines of code so as to have a clean codebase. 👍 _**I observed that it was not commented out in the last review. 👍**_

2023-05-06 00:58 UTC, OyePriscilla commented on src/modules/render.js
> +    // });
- [ ] Kindly remove this commented lines of code so as to have a clean codebase. 👍 _**I observed that it was not commented out in the last review. 👍**_

2023-05-06 01:34 UTC, braincee approved these changes
Hi @romans-adi 👋  , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-06 02:19 UTC, merged